version: "3.9"

services:
  api:
    build:
      context: .devcontainer
    container_name: izr-api-dev
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
      - cache:/home/vscode/.cache
    command: sleep infinity
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - DB_ADMIN_USERNAME=${DB_ADMIN_USERNAME}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
      - DB_SERVER=db
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - APP_VERSION=${APP_VERSION}
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:16-alpine
    container_name: izr-api-db
    volumes:
      - db_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_ADMIN_USERNAME}
      - POSTGRES_PASSWORD=${DB_ADMIN_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  cache:
  db_data: