"""2 rename event to post

Revision ID: 66adfa8a8913
Revises: da5a8e2d5857
Create Date: 2026-02-19 10:25:32.835336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "66adfa8a8913"
down_revision: Union[str, Sequence[str], None] = "da5a8e2d5857"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _create_supportedlanguages_type_if_missing()
    op.create_table(
        "posts",
        sa.Column("mosque_id", sa.Uuid(), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum("EVENT", "INFO", "ANNOUNCEMENT", name="postcontenttype"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("valid_to", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_posts_id"), "posts", ["id"], unique=False)
    op.create_table(
        "post_translations",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "language",
            postgresql.ENUM(
                "AR", "DE", "EN", name="supportedlanguages", create_type=False
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("media", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_post_translations_id"), "post_translations", ["id"], unique=False
    )
    op.drop_index(op.f("ix_event_translations_id"), table_name="event_translations")
    op.drop_table("event_translations")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_translations",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "language",
            postgresql.ENUM("AR", "DE", "EN", name="supportedlanguages"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("media", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("event_translations_event_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("event_translations_pkey")),
    )
    op.create_index(
        op.f("ix_event_translations_id"), "event_translations", ["id"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("mosque_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "valid_to", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("events_pkey")),
    )
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)
    op.drop_index(op.f("ix_post_translations_id"), table_name="post_translations")
    op.drop_table("post_translations")
    op.drop_index(op.f("ix_posts_id"), table_name="posts")
    op.drop_table("posts")
    # ### end Alembic commands ###


def _create_supportedlanguages_type_if_missing() -> None:
    """Ensure supportedlanguages enum exists for PostgreSQL."""
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'supportedlanguages') THEN
                CREATE TYPE supportedlanguages AS ENUM ('AR', 'DE', 'EN');
            END IF;
        END $$;
        """
    )
