"""4 apply versionning to prayer times table

Revision ID: 70e91e92af91
Revises: 08c238d3ea48
Create Date: 2026-03-31 10:45:42.994539

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "70e91e92af91"
down_revision: Union[str, Sequence[str], None] = "08c238d3ea48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prayer_times",
        sa.Column("valid_from", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "prayer_times",
        sa.Column("valid_to", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "prayer_times",
        sa.Column("update_reason", sqlmodel.AutoString(), nullable=True),
    )
    op.execute(
        """
        UPDATE prayer_times
        SET valid_from = NOW(),
            valid_to = '9999-12-31T00:00:00+00:00'
        WHERE valid_from IS NULL OR valid_to IS NULL
        """
    )
    op.drop_index(op.f("ix_prayer_times_id"), table_name="prayer_times")
    op.drop_index(op.f("ix_prayer_times_upload_id"), table_name="prayer_times")
    op.drop_constraint(
        op.f("prayer_times_upload_id_fkey"), "prayer_times", type_="foreignkey"
    )
    op.drop_column("prayer_times", "upload_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prayer_times",
        sa.Column("upload_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("prayer_times_upload_id_fkey"),
        "prayer_times",
        "prayer_time_uploads",
        ["upload_id"],
        ["id"],
    )
    op.create_index(
        op.f("ix_prayer_times_upload_id"), "prayer_times", ["upload_id"], unique=False
    )
    op.create_index(op.f("ix_prayer_times_id"), "prayer_times", ["id"], unique=False)
    op.drop_column("prayer_times", "update_reason")
    op.drop_column("prayer_times", "valid_to")
    op.drop_column("prayer_times", "valid_from")
    # ### end Alembic commands ###
