"""add_mosques_and_prayer_time_config_tables

Revision ID: 76c36a0dc911
Revises:
Create Date: 2025-10-27 07:53:12.444220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76c36a0dc911"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mosques",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mosques_id"), "mosques", ["id"], unique=False)
    op.create_index(op.f("ix_mosques_name"), "mosques", ["name"], unique=False)
    op.create_table(
        "prayer_time_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mosque_id", sa.Integer(), nullable=False),
        sa.Column(
            "calculation_method",
            sa.Enum(
                "JAFARI",
                "KARACHI",
                "ISNA",
                "MWL",
                "MAKKAH",
                "EGYPT",
                "TEHRAN",
                "GULF",
                "KUWAIT",
                "QATAR",
                "SINGAPORE",
                "FRANCE",
                "TURKEY",
                "RUSSIA",
                "MOONSIGHTING",
                "DUBAI",
                "JAKIM",
                "TUNISIA",
                "ALGERIA",
                "KEMENAG",
                "MOROCCO",
                "PORTUGAL",
                "JORDAN",
                "CUSTOM",
                name="calculationmethod",
            ),
            nullable=False,
        ),
        sa.Column("school", sa.Enum("SHAFI", "HANAFI", name="school"), nullable=False),
        sa.Column(
            "midnight_mode",
            sa.Enum("STANDARD", "JAFARI", name="midnightmode"),
            nullable=False,
        ),
        sa.Column(
            "latitude_adjustment_method",
            sa.Enum(
                "MIDDLE_OF_THE_NIGHT",
                "ONE_SEVENTH",
                "ANGLE_BASED",
                name="latitudeadjustmentmethod",
            ),
            nullable=False,
        ),
        sa.Column("tune", sa.Boolean(), nullable=False),
        sa.Column("imsak_tune", sa.Integer(), nullable=True),
        sa.Column("fajr_tune", sa.Integer(), nullable=True),
        sa.Column("sunrise_tune", sa.Integer(), nullable=True),
        sa.Column("dhuhr_tune", sa.Integer(), nullable=True),
        sa.Column("asr_tune", sa.Integer(), nullable=True),
        sa.Column("maghrib_tune", sa.Integer(), nullable=True),
        sa.Column("isha_tune", sa.Integer(), nullable=True),
        sa.Column("midnight_tune", sa.Integer(), nullable=True),
        sa.Column("fajr_angle", sa.Float(), nullable=True),
        sa.Column("maghrib_angle", sa.Float(), nullable=True),
        sa.Column("isha_angle", sa.Float(), nullable=True),
        sa.Column(
            "shafaq",
            sa.Enum("GENERAL", "AHMER", "ABYAD", name="shafaq"),
            nullable=False,
        ),
        sa.Column(
            "calendar_method",
            sa.Enum("HJCoSA", "UAQ", "DIYANET", "MATHEMATICAL", name="calendarmethod"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mosque_id"],
            ["mosques.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prayer_time_configurations_id"),
        "prayer_time_configurations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prayer_time_configurations_mosque_id"),
        "prayer_time_configurations",
        ["mosque_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_prayer_time_configurations_mosque_id"),
        table_name="prayer_time_configurations",
    )
    op.drop_index(
        op.f("ix_prayer_time_configurations_id"),
        table_name="prayer_time_configurations",
    )
    op.drop_table("prayer_time_configurations")
    op.drop_index(op.f("ix_mosques_name"), table_name="mosques")
    op.drop_index(op.f("ix_mosques_id"), table_name="mosques")
    op.drop_table("mosques")
    # ### end Alembic commands ###
