"""add prayer_config_id to mosque table

Revision ID: 77675e4c2cd3
Revises: 205d3686e9b7
Create Date: 2026-02-01 21:06:36.400809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77675e4c2cd3"
down_revision: Union[str, Sequence[str], None] = "205d3686e9b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mosques", sa.Column("prayer_config_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mosques", "prayer_config_id")
    # ### end Alembic commands ###
