"""delete media table

Revision ID: 781ef37cb34c
Revises: e49e9791ab81
Create Date: 2026-02-08 13:59:12.893235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "781ef37cb34c"
down_revision: Union[str, Sequence[str], None] = "e49e9791ab81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_id"), table_name="media")
    op.drop_table("media")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("mosque_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("object_key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("IMAGE", "VIDEO", name="mediafiletype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("media_pkey")),
    )
    op.create_index(op.f("ix_media_id"), "media", ["id"], unique=False)
    # ### end Alembic commands ###
