"""add media table

Revision ID: a33228ea9c9e
Revises: c5ca934834a0
Create Date: 2026-02-04 18:49:49.495823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a33228ea9c9e"
down_revision: Union[str, Sequence[str], None] = "c5ca934834a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("mosque_id", sa.Integer(), nullable=False),
        sa.Column("object_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "type", sa.Enum("IMAGE", "VIDEO", name="mediafiletype"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_id"), "media", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_id"), table_name="media")
    op.drop_table("media")
    # ### end Alembic commands ###
