"""4 drop prayer times upload table

Revision ID: b116f0757705
Revises: 70e91e92af91
Create Date: 2026-04-04 23:28:08.304638

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b116f0757705"
down_revision: Union[str, Sequence[str], None] = "70e91e92af91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prayer_time_uploads_id"), table_name="prayer_time_uploads")
    op.drop_index(
        op.f("ix_prayer_time_uploads_mosque_id"), table_name="prayer_time_uploads"
    )
    op.drop_index(
        op.f("ix_prayer_time_uploads_uploaded_at"), table_name="prayer_time_uploads"
    )
    op.drop_table("prayer_time_uploads")
    op.alter_column(
        "prayer_times",
        "valid_from",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "prayer_times",
        "valid_to",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "prayer_times",
        "valid_to",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "prayer_times",
        "valid_from",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.create_table(
        "prayer_time_uploads",
        sa.Column("mosque_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("stored_filename", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "file_type",
            postgresql.ENUM("CSV", "XLS", name="filetypeenum"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "uploaded_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["mosque_id"],
            ["mosques.id"],
            name=op.f("prayer_time_uploads_mosque_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("prayer_time_uploads_pkey")),
    )
    op.create_index(
        op.f("ix_prayer_time_uploads_uploaded_at"),
        "prayer_time_uploads",
        ["uploaded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prayer_time_uploads_mosque_id"),
        "prayer_time_uploads",
        ["mosque_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prayer_time_uploads_id"), "prayer_time_uploads", ["id"], unique=False
    )
    # ### end Alembic commands ###
