"""add prayer_iqamas table

Revision ID: c5ca934834a0
Revises: f2f950c9deb3
Create Date: 2026-02-04 13:30:46.826683

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5ca934834a0"
down_revision: Union[str, Sequence[str], None] = "f2f950c9deb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prayer_iqamas",
        sa.Column("mosque_id", sa.Integer(), nullable=False),
        sa.Column(
            "prayer_name",
            sa.Enum(
                "FAJR", "DHUHR", "ASR", "MAGHRIB", "ISHA", "JUMAH", name="prayername"
            ),
            nullable=False,
        ),
        sa.Column("mode", sa.Enum("FIXED", "OFFSET", name="iqamamode"), nullable=False),
        sa.Column("offset_minutes", sa.Integer(), nullable=True),
        sa.Column("fixed_time", sa.Time(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mosque_id"],
            ["mosques.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prayer_iqamas_id"), "prayer_iqamas", ["id"], unique=False)
    op.create_index(
        op.f("ix_prayer_iqamas_mosque_id"), "prayer_iqamas", ["mosque_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prayer_iqamas_mosque_id"), table_name="prayer_iqamas")
    op.drop_index(op.f("ix_prayer_iqamas_id"), table_name="prayer_iqamas")
    op.drop_table("prayer_iqamas")
    # ### end Alembic commands ###
