"""add sunrise filed to prayer time table

Revision ID: eeed5cc17a68
Revises: 77675e4c2cd3
Create Date: 2026-02-01 22:09:56.863845

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "eeed5cc17a68"
down_revision: Union[str, Sequence[str], None] = "77675e4c2cd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
