"""add tables: mosques, prayer_configs, prayer_timesand prayer_time_uploads

Revision ID: f2f950c9deb3
Revises:
Create Date: 2026-02-03 00:19:59.498278

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f2f950c9deb3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mosques",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prayer_config_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mosques_id"), "mosques", ["id"], unique=False)
    op.create_index(op.f("ix_mosques_name"), "mosques", ["name"], unique=False)
    op.create_table(
        "prayer_configurations",
        sa.Column("mosque_id", sa.Integer(), nullable=False),
        sa.Column(
            "calculation_method",
            sa.Enum(
                "JAFARI",
                "KARACHI",
                "ISNA",
                "MWL",
                "MAKKAH",
                "EGYPT",
                "TEHRAN",
                "GULF",
                "KUWAIT",
                "QATAR",
                "SINGAPORE",
                "FRANCE",
                "TURKEY",
                "RUSSIA",
                "MOONSIGHTING",
                "DUBAI",
                "JAKIM",
                "TUNISIA",
                "ALGERIA",
                "KEMENAG",
                "MOROCCO",
                "PORTUGAL",
                "JORDAN",
                "CUSTOM",
                name="calculationmethod",
            ),
            nullable=False,
        ),
        sa.Column("school", sa.Enum("SHAFI", "HANAFI", name="school"), nullable=False),
        sa.Column(
            "midnight_mode",
            sa.Enum("STANDARD", "JAFARI", name="midnightmode"),
            nullable=False,
        ),
        sa.Column(
            "latitude_adjustment_method",
            sa.Enum(
                "MIDDLE_OF_THE_NIGHT",
                "ONE_SEVENTH",
                "ANGLE_BASED",
                name="latitudeadjustmentmethod",
            ),
            nullable=False,
        ),
        sa.Column("tune", sa.Boolean(), nullable=False),
        sa.Column("imsak_tune", sa.Integer(), nullable=True),
        sa.Column("fajr_tune", sa.Integer(), nullable=True),
        sa.Column("sunrise_tune", sa.Integer(), nullable=True),
        sa.Column("dhuhr_tune", sa.Integer(), nullable=True),
        sa.Column("asr_tune", sa.Integer(), nullable=True),
        sa.Column("maghrib_tune", sa.Integer(), nullable=True),
        sa.Column("isha_tune", sa.Integer(), nullable=True),
        sa.Column("midnight_tune", sa.Integer(), nullable=True),
        sa.Column("fajr_angle", sa.Float(), nullable=True),
        sa.Column("maghrib_angle", sa.Float(), nullable=True),
        sa.Column("isha_angle", sa.Float(), nullable=True),
        sa.Column(
            "shafaq",
            sa.Enum("GENERAL", "AHMER", "ABYAD", name="shafaq"),
            nullable=False,
        ),
        sa.Column(
            "calendar_method",
            sa.Enum("HJCoSA", "UAQ", "DIYANET", "MATHEMATICAL", name="calendarmethod"),
            nullable=False,
        ),
        sa.Column("adjustment", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mosque_id"],
            ["mosques.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prayer_configurations_id"),
        "prayer_configurations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prayer_configurations_mosque_id"),
        "prayer_configurations",
        ["mosque_id"],
        unique=False,
    )
    op.create_table(
        "prayer_time_uploads",
        sa.Column("mosque_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "stored_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "file_type", sa.Enum("CSV", "XLS", name="filetypeenum"), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mosque_id"],
            ["mosques.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prayer_time_uploads_mosque_id"),
        "prayer_time_uploads",
        ["mosque_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prayer_time_uploads_uploaded_at"),
        "prayer_time_uploads",
        ["uploaded_at"],
        unique=False,
    )
    op.create_table(
        "prayer_times",
        sa.Column("fajr", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("shuruq", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dhuhr", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("asr", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("maghrib", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("isha", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("gregorian_date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hijri_date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mosque_id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mosque_id"],
            ["mosques.id"],
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["prayer_time_uploads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prayer_times_mosque_id"), "prayer_times", ["mosque_id"], unique=False
    )
    op.create_index(
        op.f("ix_prayer_times_upload_id"), "prayer_times", ["upload_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prayer_times_upload_id"), table_name="prayer_times")
    op.drop_index(op.f("ix_prayer_times_mosque_id"), table_name="prayer_times")
    op.drop_table("prayer_times")
    op.drop_index(
        op.f("ix_prayer_time_uploads_uploaded_at"), table_name="prayer_time_uploads"
    )
    op.drop_index(
        op.f("ix_prayer_time_uploads_mosque_id"), table_name="prayer_time_uploads"
    )
    op.drop_table("prayer_time_uploads")
    op.drop_index(
        op.f("ix_prayer_configurations_mosque_id"), table_name="prayer_configurations"
    )
    op.drop_index(
        op.f("ix_prayer_configurations_id"), table_name="prayer_configurations"
    )
    op.drop_table("prayer_configurations")
    op.drop_index(op.f("ix_mosques_name"), table_name="mosques")
    op.drop_index(op.f("ix_mosques_id"), table_name="mosques")
    op.drop_table("mosques")
    # ### end Alembic commands ###
