---
services:
  admin:
    build:
      context: ../../izr-admin-app
      args:
      - VITE_API_BASE_URL=https://api.iz-regensburg.de

    volumes:
    - cache:/code/.cache
    ports:
    - 8002:80

    depends_on:
      api:
        condition: service_started
    networks:
    - izr-api-net

volumes:
  cache:
