---
services:
  api:
    build: ..
    volumes:
    - cache:/code/.cache
    ports:
    - 8000:8000
    environment:
    - DB_ADMIN_USERNAME=${DB_ADMIN_USERNAME}
    - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
    - DB_SERVER=${DB_SERVER}
    - DB_NAME=${DB_NAME}
    - DB_PORT=${DB_PORT}
    - FRONTEND_URL=${FRONTEND_URL}
    - APP_VERSION=${APP_VERSION}
    - MINIO_ROOT_USER=${MINIO_ROOT_USER}
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    - MINIO_ENDPOINT=${MINIO_ENDPOINT}
    - MINIO_SECURE=${MINIO_SECURE}
    - MINIO_PROXY_URL=${MINIO_PROXY_URL}
    - MINIO_DEFAULT_BUCKET=${MINIO_DEFAULT_BUCKET}
    - PRAYER_TIMES_DIRECTORY=${PRAYER_TIMES_DIRECTORY}
    - DB_BACKUPS_DIRECTORY=${DB_BACKUPS_DIRECTORY}
    - MEDIA_DIRECTORY=${MEDIA_DIRECTORY}

    depends_on:
      db:
        condition: service_started
    networks:
    - izr-api-net

volumes:
  cache:
