---
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
    - MINIO_ROOT_USER=${MINIO_ROOT_USER}
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

    command: server /data --console-address ":9001"
    networks:
    - izr-api-net
    volumes:
    - minio_data:/data
    ports:
    - 9000:9000
    - 9001:9001

  minio-init:
    image: minio/mc:latest
    depends_on:
    - minio
    environment:
    - MINIO_DEFAULT_BUCKET=${MINIO_DEFAULT_BUCKET}
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set izr-minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb izr-minio/${MINIO_DEFAULT_BUCKET}/${DB_BACKUPS_DIRECTORY} || true;
      /usr/bin/mc mb izr-minio/${MINIO_DEFAULT_BUCKET}/${PRAYER_TIMES_DIRECTORY} || true;
      /usr/bin/mc mb izr-minio/${MINIO_DEFAULT_BUCKET}/${MEDIA_DIRECTORY} || true;
      exit 0;
      "
    networks:
    - izr-api-net

volumes:
  minio_data:
    driver: local
